### ISSUE TITLE
`set-output` commands are deprecated

### ISSUE THREAD

**Issue by ajschmidt8** [rapidsai/actions#2]
Similar to https://github.com/rapidsai/shared-action-workflows/issues/11.

As mentioned in the blog post below, the `set-output` commands are deprecated. It seems the new recommended approach is to use the `$GITHUB_OUTPUT` environment variable. We should update our code accordingly.

**Docs:**
- https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Lines to replace:**
- https://github.com/rapidsai/actions/blob/77ad7542ade720acef698eb4fb9e17f2ebf36866/.github/workflows/get-run-info.yaml#L53

**Comment by Ethyling** [comment]
Fixed in https://github.com/rapidsai/actions/pull/3
